cli: elliminate need to specify OPTRTCDS env var in /etc/advligorts/env
The target location of /opt/rtcds/$site/$ifo is hard coded deep throughout
the code.  Until we address that issue, we can just derive the target from
SITE and IFO, which simplifies the config.

diff --git a/support/bin/rtcds.in b/support/bin/rtcds.in
--- a/support/bin/rtcds.in
+++ b/support/bin/rtcds.in
@@ -1,11 +1,9 @@
 #!/bin/bash -e
 
 RTS_VERSION=${RTS_VERSION:-__VERSION__}
-ENV_FILE=${RTS_ENV:-/etc/advligorts/env}
-RCG_SRC=${RCG_SRC:-/usr/share/advligorts/src}
-RCG_BUILDD=${RCG_BUILDD:-/var/cache/advligorts/rcg-$RTS_VERSION}
-RTS_USER=${RTS_USER:-controls}
 
+# this should define all USER_VARS (see below)
+ENV_FILE=${RTS_ENV:-/etc/advligorts/env}
 source "$ENV_FILE" 2>/dev/null || true
 
 SITE=${SITE^^*}
@@ -13,15 +11,22 @@ site=${SITE,,*}
 IFO=${IFO^^*}
 ifo=${IFO,,*}
 
+RCG_SRC=${RCG_SRC:-/usr/share/advligorts/src}
+RCG_BUILDD=${RCG_BUILDD:-/var/cache/advligorts/rcg-$RTS_VERSION}
+# FIXME: the RCG hard-codes /opt/rtcds as the root
+RCG_TARGET=/opt/rtcds/${site}/${ifo}
+RTS_USER=${RTS_USER:-controls}
+
 # search paths for C source code
 CDS_SRC=${CDS_SRC:-$RCG_LIB_PATH}
 CDS_IFO_SRC=${CDS_IFO_SRC:-$CDS_SRC}
 
 # add RCG module source to lib path
+# FIXME: rename RCG_MOD_PATH
 RCG_LIB_PATH=$RCG_LIB_PATH:${RCG_SRC}/src/epics/simLink/:${RCG_SRC}/src/epics/simLink/lib
 
-USER_VARS=(SITE IFO OPTRTCDS RCG_LIB_PATH)
-LIST_VARS=(RTS_VERSION ${USER_VARS[@]} RCG_SRC RCG_BUILDD RTS_USER)
+USER_VARS=(SITE IFO RCG_LIB_PATH)
+LIST_VARS=(RTS_VERSION ${USER_VARS[@]} RCG_SRC RCG_BUILDD RCG_TARGET RTS_USER)
 EXPORT_VARS=(${USER_VARS[@]} site ifo CDS_SRC CDS_IFO_SRC)
 
 ##################################################
@@ -49,20 +54,40 @@ check_env() {
     done
 }
 
-prep_target(){
-    log "creating OPTRTCDS..."
-    mkdir -p ${OPTRTCDS}/{target,chans}/tmp
+prep_buildd() {
+    if [ -d "$RCG_BUILDD" ] ; then
+        return
+    fi
+    log "creating RCG_BUILDD $RCG_BUILDD..."
+    if sudo -u $RTS_USER mkdir -p "$RCG_BUILDD" 2>/dev/null ; then
+        sudo -u $RTS_USER chown $RTS_USER:$RTS_USER "$RCG_BUILDD"
+    elif sudo mkdir -p "$RCG_BUILDD" 2>/dev/null ; then
+        sudo chown $RTS_USER:$RTS_USER "$RCG_BUILDD"
+    else
+        log "Could not create build directory '$RCG_BUILDD' (owner: $RTS_USER:$RTS_USER)."
+        log "Please create manually to continue."
+        exit 1
+    fi
+    log "configuring RCG_BUILDD $RCG_BUILDD..."
+    cd "$RCG_BUILDD"
+    sudo -u $RTS_USER "$RCG_SRC"/configure
 }
 
-prep_buildd() {
-    sudo mkdir -p "$RCG_BUILDD"
-    sudo chown "$RTS_USER" "$RCG_BUILDD"
-    if [ -e "$RCG_BUILDD"/Makefile ] ; then
-	return
+prep_target(){
+    if [ -d "$RCG_TARGET" ] ; then
+        return
     fi
-    log "configuring RCG_BUILDD..."
-    cd "$RCG_BUILDD"
-    "$RCG_SRC"/configure
+    log "creating RCG_TARGET $RCG_TARGET..."
+    if sudo -u $RTS_USER mkdir -p "$RCG_TARGET" 2>/dev/null ; then
+        sudo -u $RTS_USER chown $RTS_USER:$RTS_USER "$RCG_TARGET"
+    elif sudo mkdir -p "$RCG_TARGET" 2>/dev/null ; then
+        sudo chown $RTS_USER:$RTS_USER "$RCG_TARGET"
+    else
+        log "Could not create target directory '$RCG_TARGET' (owner: $RTS_USER:$RTS_USER)."
+        log "Please create manually to continue."
+        exit 1
+    fi
+    sudo -u $RTS_USER mkdir -p ${RCG_TARGET}/{target,chans/tmp}
 }
 
 ########
@@ -224,6 +249,7 @@ case $cmd in
 	    exit 2
 	fi
 	check_env
+	prep_target
 	install_sys $@
 	;;
     'start')
